#:schema node_modules/wrangler/config-schema.json
name = "cf-create-worker"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "138e27f4-2908-4254-9910-5e6a46b1510d"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.r2.junsen.online"

[dev]
port = 5000
